# Generated by Django 4.0.4 on 2022-05-21 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('first_text', models.TextField()),
                ('image', models.ImageField(upload_to='photos/<django.db.models.fields.SlugField>')),
                ('second_title', models.CharField(blank=True, max_length=100)),
                ('second_text', models.TextField(blank=True)),
                ('third_title', models.CharField(blank=True, max_length=100)),
                ('third_text', models.TextField(blank=True)),
                ('file_field', models.FileField(upload_to='files/<django.db.models.fields.SlugField>')),
                ('video_url', models.URLField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            options={
                'ordering': ['first_title'],
            },
        ),
    ]
