# Generated by Django 4.0.4 on 2022-05-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_theme_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description_kz',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='title_kz',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='title_ru',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='first_text_kz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='first_text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='first_title_kz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='first_title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='second_text_kz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='second_text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='second_title_kz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='second_title_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='third_text_kz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='third_text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='third_title_kz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='third_title_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
